name: Update IPTV Sources

on:
  schedule:
    - cron: '0 */12 * * *'  # 每12小时运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  update-iptv:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v2.5.0
    
    - name: Set up Python
      uses: actions/setup-python@v2.3.3
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run IPTV updater
      run: |
        python -u get_iptv.py
        
        # 创建空文件（如果脚本未能创建）
        if [ ! -f "iptv_stream.m3u" ]; then
          echo "#EXTM3U" > iptv_stream.m3u
          echo "# No streams found" >> iptv_stream.m3u
        fi
        
        if [ ! -f "moyun.txt" ]; then
          echo "# IPTV直播源列表" > moyun.txt
          echo "更新时间: $(date '+%Y-%m-%d %H:%M:%S')" >> moyun.txt
          echo "未找到有效直播源" >> moyun.txt
        fi
    
    - name: List files
      run: |
        echo "Current directory contents:"
        ls -la
        
        echo "Content of moyun.txt:"
        cat moyun.txt
    
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add moyun.txt iptv_stream.m3u
        git commit -m "Update IPTV sources $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
        git push || echo "No changes to push"
    
    - name: Create Release Tag
      id: tag
      run: |
        timestamp=$(date '+%Y%m%d_%H%M%S')
        echo "tag_name=v${timestamp}" >> $GITHUB_OUTPUT
        echo "release_name=IPTV Update ${timestamp}" >> $GITHUB_OUTPUT
    
    - name: Create Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "moyun.txt,iptv_stream.m3u"
        token: ${{ secrets.GITHUB_TOKEN }}
        name: ${{ steps.tag.outputs.release_name }}
        tag: ${{ steps.tag.outputs.tag_name }}
        generateReleaseNotes: true
