name: Update IPTV Sources

on:
  schedule:
    - cron: '0 */12 * * *'  # 每12小时运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  update-iptv:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run IPTV updater
      run: python get_iptv.py
    
    - name: Check files exist
      run: |
        if [ ! -f "moyun.txt" ]; then
          echo "Error: moyun.txt does not exist"
          exit 1
        fi
        if [ ! -f "iptv_stream.m3u" ]; then
          echo "Error: iptv_stream.m3u does not exist"
          exit 1
        fi
        ls -la
    
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add moyun.txt iptv_stream.m3u
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update IPTV sources $(date '+%Y-%m-%d %H:%M:%S')" && git push)
    
    - name: Create Release Tag
      id: create_tag
      run: |
        timestamp=$(date '+%Y%m%d_%H%M%S')
        echo "::set-output name=tag_name::v${timestamp}"
        echo "::set-output name=release_name::IPTV Update ${timestamp}"
    
    - name: Create Release
      uses: actions/create-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.create_tag.outputs.tag_name }}
        release_name: ${{ steps.create_tag.outputs.release_name }}
        draft: false
        prerelease: false
    
    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./moyun.txt
        asset_name: moyun.txt
        asset_content_type: text/plain